import { ProgrammingLanguage } from '../models/tasks-model';

export const PROGRAMMING_LANGUAGES: ProgrammingLanguage[] = [
  { id: 45, name: 'Assembly' },
  { id: 46, name: 'Bash' },
  { id: 47, name: 'Basic' },
  { id: 110, name: 'C' },
  { id: 54, name: 'C++' },
  { id: 86, name: 'Clojure' },
  { id: 51, name: 'C#' },
  { id: 77, name: 'COBOL' },
  { id: 55, name: 'Common Lisp' },
  { id: 90, name: 'Dart' },
  { id: 56, name: 'D' },
  { id: 57, name: 'Elixir' },
  { id: 58, name: 'Erlang' },
  { id: 44, name: 'Executable' },
  { id: 87, name: 'F#' },
  { id: 59, name: 'Fortran' },
  { id: 107, name: 'Go' },
  { id: 88, name: 'Groovy' },
  { id: 61, name: 'Haskell' },
  { id: 62, name: 'Java' },
  { id: 63, name: 'JavaScript' },
  { id: 111, name: 'Kotlin' },
  { id: 64, name: 'Lua' },
  { id: 89, name: 'Multi-file program' },
  { id: 79, name: 'Objective-C' },
  { id: 65, name: 'OCaml' },
  { id: 66, name: 'Octave' },
  { id: 67, name: 'Pascal' },
  { id: 85, name: 'Perl' },
  { id: 98, name: 'PHP' },
  { id: 69, name: 'Prolog' },
  { id: 71, name: 'Python' },
  { id: 80, name: 'R' },
  { id: 73, name: 'Rust' },
  { id: 112, name: 'Scala' },
  { id: 82, name: 'SQL' },
  { id: 83, name: 'Swift' },
  { id: 74, name: 'TypeScript' },
  { id: 84, name: 'Visual Basic.Net' },
  { id: 43, name: 'Plain Text' },
];
